IMAGE:
  WIDTH: 640
  HEIGHT: 480
  # find your ROI parameter.

XYCAR:
  START_SPEED: 0.0
  MAX_SPEED: 0.0
  MIN_SPEED: 0.0
  SPEED_CONTROL_THRESHOLD: 0.0
  ACCELERATION_STEP: 0.00
  DECELERATION_STEP: 0.0
  # find your parameter.

# If you want to use other control methods, Change PID to another control methods.
PID:
  P_GAIN: 0.0
  I_GAIN: 0.0000
  D_GAIN: 0.00
  # find your parameter.

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 30

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  QUEUE_SIZE: 1

DEBUG: true

CAMERA:
  CAMERA_MATRIX: [[362.75082954253867, 0.0, 316.7207500000546],
                  [0.0, 362.7834715795724, 216.9389784060939],
                  [0.0, 0.0, 1.0]]
  DIST_COEFF: [-0.3274493403957699, 0.0826328081569166, 0.001002089215118404, 0.00263257842447227, 0.0]

YOLO:
  CONFIG: "/home/nvidia/xycar_ws/src/sensor_fusion_system/config/yolov3-tiny_tstl_416.cfg"
  MODEL: "/home/nvidia/xycar_ws/src/sensor_fusion_system/config/model_epoch4400.weights"
  # MODEL: "/home/nvidia/xycar_ws/src/sensor_fusion_system/config/model_epoch4400.onnx"
  LABEL: "/home/nvidia/xycar_ws/src/sensor_fusion_system/config/labels.names"
